"""Build the model comparison report from logged MLflow runs.

Reads the tracking store rather than re-running anything, so the report can never drift
from the runs it claims to describe. The champion is chosen by macro-F1, but the report
deliberately shows macro-MAE and the confidence interval next to it: a model that wins by
less than the interval width has not actually been shown to win.

Run with ``python -m src.evaluate.compare``.
"""

from __future__ import annotations

from typing import Any

import mlflow
import pandas as pd

from src.config import REPO_ROOT, ensure_parent
from src.train import registry

REPORT_PATH = REPO_ROOT / "docs" / "model_comparison.md"

_METRIC_COLUMNS = [
    ("test_macro_f1", "Macro-F1", "{:.4f}"),
    ("test_macro_mae", "Macro-MAE", "{:.4f}"),
    ("test_accuracy", "Accuracy", "{:.4f}"),
    ("test_quadratic_weighted_kappa", "QWK", "{:.4f}"),
    ("test_adjacent_accuracy", "Within 1 star", "{:.4f}"),
]


def fetch_runs() -> pd.DataFrame:
    """Latest finished run per tier, newest first."""
    experiment_name = registry.setup()
    experiment = mlflow.get_experiment_by_name(experiment_name)
    if experiment is None:
        return pd.DataFrame()

    runs = mlflow.search_runs(
        experiment_ids=[experiment.experiment_id],
        filter_string="attributes.status = 'FINISHED'",
        order_by=["attributes.start_time DESC"],
    )
    # search_runs is typed as DataFrame | list[Run]; it only returns the list form when
    # output_format="list" is passed, which it never is here.
    assert isinstance(runs, pd.DataFrame)
    if runs.empty or "tags.tier" not in runs.columns:
        return pd.DataFrame()
    return runs.dropna(subset=["tags.tier"]).drop_duplicates(subset=["tags.tier"], keep="first")


def build_report(runs: pd.DataFrame) -> str:
    """Render the comparison as markdown."""
    if runs.empty:
        return "# Model comparison\n\nNo finished runs found. Run `make train` first.\n"

    runs = runs.sort_values("tags.tier")
    lines = [
        "# Model comparison",
        "",
        "Generated by `python -m src.evaluate.compare` from the MLflow tracking store.",
        "Do not edit by hand.",
        "",
        "All figures are on the held-out **test** split, which no training or model-selection",
        "step has seen. Macro-F1 is the headline metric because ~64% of this corpus is 5-star:",
        "plain accuracy rewards a model that simply predicts 5 every time.",
        "",
        "| Tier | Run | " + " | ".join(label for _, label, _ in _METRIC_COLUMNS) + " | Macro-F1 95% CI |",
        "|---|---|" + "---|" * (len(_METRIC_COLUMNS) + 1),
    ]

    for _, run in runs.iterrows():
        cells = []
        for column, _, fmt in _METRIC_COLUMNS:
            value = run.get(f"metrics.{column}")
            cells.append(fmt.format(value) if pd.notna(value) else "-")
        low = run.get("metrics.test_macro_f1_ci_low")
        high = run.get("metrics.test_macro_f1_ci_high")
        ci = f"[{low:.4f}, {high:.4f}]" if pd.notna(low) and pd.notna(high) else "-"
        name = run.get("tags.mlflow.runName", "?")
        lines.append(
            f"| {run['tags.tier']} | `{name}` | " + " | ".join(cells) + f" | {ci} |"
        )

    champion = runs.loc[runs["metrics.test_macro_f1"].idxmax()]
    lines += [
        "",
        "## Per-class F1",
        "",
        "The minority classes (2 and 3 stars) are where these models actually differ; the",
        "5-star column is easy for everything.",
        "",
        "| Tier | " + " | ".join(f"{star}★" for star in range(1, 6)) + " |",
        "|---|" + "---|" * 5,
    ]
    for _, run in runs.iterrows():
        cells = [
            f"{run.get(f'metrics.test_f1_class_{star}'):.3f}"
            if pd.notna(run.get(f"metrics.test_f1_class_{star}"))
            else "-"
            for star in range(1, 6)
        ]
        lines.append(f"| {run['tags.tier']} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "## Champion",
        "",
        f"**Tier {champion['tags.tier']}** (`{champion.get('tags.mlflow.runName', '?')}`), "
        f"macro-F1 **{champion['metrics.test_macro_f1']:.4f}**, "
        f"macro-MAE **{champion['metrics.test_macro_mae']:.4f}**.",
        "",
        f"- Run ID: `{champion['run_id']}`",
        f"- Git SHA: `{champion.get('tags.git_sha', 'unknown')}`",
        "",
        "> Selection is by macro-F1 on the test split. Where two tiers overlap within their",
        "> confidence intervals, prefer the cheaper one - and say so explicitly in the report",
        "> rather than presenting the more expensive model as a clear winner.",
        "",
        "## Still to come (Week 2)",
        "",
        "Inference latency and artifact size per tier, which complete the",
        "accuracy/latency/size triple used to justify the final champion pick.",
        "",
    ]
    return "\n".join(lines)


def main() -> dict[str, Any]:
    runs = fetch_runs()
    report = build_report(runs)
    ensure_parent(REPORT_PATH).write_text(report, encoding="utf-8")
    print(f"[compare] {len(runs)} run(s) -> {REPORT_PATH}")
    if not runs.empty:
        for _, run in runs.sort_values("tags.tier").iterrows():
            print(
                f"[compare]   tier {run['tags.tier']}: "
                f"macro_f1={run.get('metrics.test_macro_f1', float('nan')):.4f} "
                f"macro_mae={run.get('metrics.test_macro_mae', float('nan')):.4f}"
            )
    return {"runs": len(runs), "report": str(REPORT_PATH)}


if __name__ == "__main__":
    main()
