"""Export MLflow tracking data into `docs/mlflow_exports/` for the submission checklist.

The brief's submission checklist asks for tracking "logs, screenshots or exported logs,"
separate from the written comparison report (`docs/model_comparison.md`). This is the
"exported logs" half: a machine-readable CSV of every run plus a human-readable markdown
summary of the run history and the registry's current state, generated from the tracking
store rather than hand-written, so it can't drift from what MLflow actually holds.

Run with ``python -m src.evaluate.mlflow_export``.
"""

from __future__ import annotations

import mlflow
import pandas as pd

from src.config import REPO_ROOT, ensure_parent
from src.train import registry

EXPORT_DIR = REPO_ROOT / "docs" / "mlflow_exports"
RUNS_CSV = EXPORT_DIR / "runs.csv"
SUMMARY_MD = EXPORT_DIR / "summary.md"

_TIER_NAME = {
    "1": "TF-IDF -> logistic regression",
    "2": "MiniLM embeddings -> LightGBM",
    "3": "fine-tuned DistilRoBERTa (champion)",
}


def _runs_dataframe() -> pd.DataFrame:
    client = mlflow.tracking.MlflowClient()
    experiment = client.get_experiment_by_name("moodrift")
    if experiment is None:
        raise SystemExit("[mlflow_export] no 'moodrift' experiment found - run `make train` first")
    runs = client.search_runs(
        experiment_ids=[experiment.experiment_id], max_results=500, order_by=["start_time ASC"]
    )
    rows = []
    for r in runs:
        rows.append(
            {
                "run_id": r.info.run_id,
                "tier": r.data.tags.get("tier"),
                "start_time": pd.Timestamp(r.info.start_time, unit="ms", tz="UTC"),
                "git_sha": r.data.tags.get("git_sha"),
                "reproduces": r.data.tags.get("reproduces"),
                "test_macro_f1": r.data.metrics.get("test_macro_f1"),
                "test_macro_mae": r.data.metrics.get("test_macro_mae"),
                "test_accuracy": r.data.metrics.get("test_accuracy"),
                "data_train_sha256": r.data.tags.get("data.train.sha256"),
                "data_val_sha256": r.data.tags.get("data.val.sha256"),
                "data_test_sha256": r.data.tags.get("data.test.sha256"),
            }
        )
    return pd.DataFrame(rows)


def _registry_state() -> tuple[dict[str, int], list[dict]]:
    client = mlflow.tracking.MlflowClient()
    rm = client.get_registered_model("moodrift-classifier")
    versions = []
    for mv in client.search_model_versions("name='moodrift-classifier'"):
        versions.append(
            {
                "version": mv.version,
                "tier": mv.tags.get("tier"),
                "run_id": mv.tags.get("run_id"),
                "test_macro_f1": mv.tags.get("test_macro_f1"),
                "promoted_with_force": mv.tags.get("promoted_with_force"),
                "description": mv.description,
            }
        )
    return dict(rm.aliases), versions


def export() -> None:
    """Write runs.csv and summary.md from the current tracking store."""
    registry.setup()
    ensure_parent(RUNS_CSV)

    df = _runs_dataframe()
    df.to_csv(RUNS_CSV, index=False)
    print(f"[mlflow_export] {len(df)} runs -> {RUNS_CSV}")

    aliases, versions = _registry_state()

    lines = [
        "# MLflow export",
        "",
        "Generated by `python -m src.evaluate.mlflow_export` (`make mlflow-export`) from "
        "the live tracking store (`mlflow.db`) - not hand-written, so it can't drift from "
        "what's actually logged. Machine-readable form: [`runs.csv`](runs.csv). Full "
        "comparison and gate analysis: [`../model_comparison.md`](../model_comparison.md).",
        "",
        "## Registry state",
        "",
        "`moodrift-classifier` aliases: " + ", ".join(f"`@{k}` -> v{v}" for k, v in sorted(aliases.items())) + ".",
        "",
        "| Version | Tier | Test macro-F1 | Promoted with --force | Run ID |",
        "|---|---|---|---|---|",
    ]
    for v in sorted(versions, key=lambda x: int(x["version"])):
        lines.append(
            f"| {v['version']} | {v['tier']} | {v['test_macro_f1']} | {v['promoted_with_force']} "
            f"| `{v['run_id']}` |"
        )

    lines += ["", "## Run history", "", f"{len(df)} runs logged, across tiers 1-3 plus `make reproduce` re-runs.", ""]
    lines += ["| Run | Tier | Started | Test macro-F1 | Git SHA | Reproduces |", "|---|---|---|---|---|---|"]
    for _, row in df.iterrows():
        tier_label = _TIER_NAME.get(str(row["tier"]), row["tier"])
        f1 = f"{row['test_macro_f1']:.4f}" if pd.notna(row["test_macro_f1"]) else "-"
        reproduces = f"`{row['reproduces'][:8]}`" if pd.notna(row["reproduces"]) else "-"
        git_sha = str(row["git_sha"])[:10] if pd.notna(row["git_sha"]) else "-"
        started = row["start_time"].strftime("%Y-%m-%d %H:%M UTC")
        lines.append(
            f"| `{row['run_id'][:8]}` | {tier_label} | {started} | {f1} | `{git_sha}` | {reproduces} |"
        )

    reproduce_runs = df[df["reproduces"].notna()]
    lines += [
        "",
        "## Reproduction runs",
        "",
        f"{len(reproduce_runs)} of the {len(df)} runs above are `make reproduce` re-runs "
        "(the `reproduces` column names the original run they re-ran). See the README's "
        "reproduce table for the delta-vs-tolerance verdicts; this export only shows "
        "which runs exist and which run they trace back to.",
    ]

    SUMMARY_MD.write_text("\n".join(lines) + "\n")
    print(f"[mlflow_export] summary -> {SUMMARY_MD}")


if __name__ == "__main__":
    export()
